version: 2
updates:
- package-ecosystem: yarn
  target_branch: "alpha"
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - johannrichard
